apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-account
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-pod-controller
  # ClusterRoles are NOT namespaced so we should omit it!
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-pod-access
  # No need for namespaces here either
subjects:
- kind: ServiceAccount
  name: chaos-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: chaos-pod-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-monkey
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: chaos-monkey
  replicas: 1
  template:
    metadata:
      labels:
        app: chaos-monkey
    spec:
      serviceAccountName: chaos-account
      containers:
      - name: chaos-monkey
        image: chaos-monkey:latest
        imagePullPolicy: IfNotPresent
        env:
          # Which namespace do we kill pods in
          - name: NAMESPACE
            value: kube-public
          # How many seconds between pod executions
          - name: DELAY
            value: "30"
